### ISSUE TITLE
Can't use this with karma?

### ISSUE THREAD

**Issue by jbures** [matthewp/custom-attributes#22]
Hi there, i'm trying to use this module for a work project, and it works smoothly for development.

But i'm not able to test a file that imports this module for some reason... 
Is there some funny workaround i need to make to get karma to see this module?
I have in the same file (typescript) imports for this module and lodash functions, but this one is just "not found" by karma... 

Ideas?

**Comment by matthewp** [comment]
I'm not familiar with karma unfortunately. I don't see what would make this any different from other dependencies...

**Comment by jbures** [comment]
FIgured it out, since this module is not minified and transpiled to es5, like most, the karma-typescript compiler gets messed up because it's not expecting .js files to have imports for example.
So there's an a es6 transformer plugin for it.
