### ISSUE TITLE
Doesn't recognise nested elements on added nodes 

### ISSUE THREAD

**Issue by bedeoverend** [matthewp/custom-attributes#5]
When a new node is added to the tree, if that node already has a subtree attached to it, the MutationObserver only has the root node in the `addedNodes` list, but `custom-attributes` doesn't check the subtree for any elements that have attributes in the registry.

Believe all that's needed is to call `_upgradeAttr` on any _added_ node i.e. in the `upgradeElement` function, with that element as the root, not the `ownerDocument`

**Comment by matthewp** [comment]
Sounds right to me.
