### ISSUE TITLE
Make CustomAttributeRegistry standalone

### ISSUE THREAD

**Issue by bedeoverend** [matthewp/custom-attributes#7]
Right now `CustomAttributeRegistry` and `customAttributes` are automatically attached as globals on `window`. To allow users to consume as a module, rather than as a polyfill-style global, it would be good to be able to `import` `CustomAttributeRegistry` as a standalone module to implement your own registries. The current setup could be left as is, just with this to supplement.

Use case: my own use case, I'm looking to use `CustomAttributeRegistry` in a package, but would prefer to not expose it as a global registry by default.

@matthewp thoughts?

**Comment by matthewp** [comment]
I agree, how would you go about doing this though? I want to make sure that this is useable as-is in browsers and not require a bundler.

We could have two separate builds, one that is `attr.es.js` that is an ES module and `attr.js` that is the global like we have now.  This is how [Bram works](https://github.com/matthewp/bram/blob/master/Makefile#L3-L7).  Does that satisfy your needs? Will an ES module work?

What should be exported, just `CustomAttributeRegistry` or should there be a default instance using the global document as well?

**Comment by bedeoverend** [comment]
Agreed - I think an ES module would be best. Also think that it should just export `CustomAttributeRegistry` - given how simple it is to setup an initial registry, and as long as the 'polyfill'-style option is kept as well, I don't think there'd be anything lacking by just the `CustomAttributeRegistry` class?

I think and interface that looks something like:

```js
import 'custom-attributes'; // Sets up globals
import CustomAttributeRegistry from 'custom-attributes/registry';
```

or perhaps

```js
import 'custom-attributes'; // Sets up globals
import { CustomAttributeRegistry } from 'custom-attributes/lib';
```

The latter providing an easy interface to have more helpers in future if needed.

Both of those are looking at using it from a bundler sense, I guess you can then just turn the `registry` into a UMD bundle too, a là Bram? You wouldn't need a UMD for the default global instance version right, given that it _just_ attaches to `window`?

**Comment by matthewp** [comment]
Yeah, the default version would be an IIFE and not UMD.  I like 'custom-attributes/registry' a little better IMO.

I'll try to get to this tonight or tomorrow morning.
